- name: Disable ProxmoxVE entreprise repository
  shell: >
    if [ -e {{ proxmox_base_entperise_repo_file }} ]; then
      mv {{ proxmox_base_entperise_repo_file }} {{ proxmox_base_entperise_repo_file }}.disabled
    fi
  when:
    - not proxmox_base_licensed
  tags: [never, setup]


- name: Re-enable ProxmoxVE entreprise repository
  shell: >
    if [ -e {{ proxmox_base_entperise_repo_file }}.disabled ]; then
      mv {{ proxmox_base_entperise_repo_file }}.disabled {{ proxmox_base_entperise_repo_file }}
    fi
  tags: [never, teardown]
